function pop_adam_prefs()
% POP_ADAM_PREFS - Minimal preferences GUI for ADAM plugin.
% Stores prefs under group 'eeglab_adam'.

g = struct();
g.adamRoot = getpref('eeglab_adam','adamRoot',''); % folder path (optional if ADAM already on path)
geometry = { [1] [1] [1] [1] [1] };
uilist = { ...
    { 'style' 'text' 'string' 'ADAM root folder (optional, added to path):' } ...
    { 'style' 'edit' 'tag' 'adamRoot' 'string' g.adamRoot } ...
    { 'style' 'pushbutton' 'string' 'Browse...' 'callback' ...
      ['[f, p] = uigetfile(''*.*'',''Select any ADAM file'');' ...
       'if isequal(f,0), return; end; set(findobj(gcbf,''tag'',''adamRoot''),''string'',p);'] } ...
    { 'style' 'text' 'string' 'Defaults are applied in GUIs (folds, resample, baseline, etc.).' } ...
    { 'style' 'text' 'string' 'Click OK to save.' } ...
};
res = inputgui('geometry', geometry, 'uilist', uilist, 'title', 'ADAM Preferences');
if isempty(res), return; end
adamRoot = get(findobj(gcbf,'tag','adamRoot'),'string');
setpref('eeglab_adam','adamRoot',adamRoot);
if ~isempty(adamRoot) && isfolder(adamRoot), addpath(genpath(adamRoot)); rehash; end
close(gcbf);
end
